version: 2.1

jobs:
  test:
    working_directory: ~/circleci-python
    docker:
      - image: "circleci/python:3.8"
    steps:
      - checkout
      - run: python3 basi-add.py

  build:
    docker:
      - image: "circleci/node:latest"
    steps:
      - run:
          name: Install Docker client
          command: |
            docker login -u $ DOCKER_USER -p $DOCKER_PASS
            docker build -t my-first-build-image .
             
      


workflows:
  build_and_test:
    jobs:
      - test
      - build:
          requires:
            - test
