version: 2.1

jobs:
  test:
    working_directory: ~/circleci-python
    docker:
      - image: "python:latest"
    steps:
      - checkout
      - run: python3 basi-add.py

  build:
    working_directory: ~/circleci-python
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - run: 
          name: docker version
          command: |
            docker --version
      - run: docker run -d dockerswarm/swarm:master join --advertise=192.168.1.105:2375 consul://192.168.1.103:8500
      # - run: docker status


        
# sudo service docker status
# docker run --ulimit nofile=32768:32768 --rm debian sh -c "ulimit -n" 32768

      - run: 
          name: Build image
          command: |
            docker build -t first_build .   
            echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
            docker context ls
            docker build -t first_build .          
      
#start it

workflows:
  build_and_test:
    jobs:
      - test
      - build:
          requires:
            - test
