version: 2.1

jobs:
  test:
    working_directory: ~/circleci-python
    docker:
      - image: "python:latest"
    steps:
      - checkout
      - run: python3 basi-add.py

  build:
    working_directory: ~/circleci-python
    docker:
      - image: ubuntu:hirsute-20211208
    steps:
      - checkout
      - run: 
          name: install docker
          command: |
            sudo apt-get update
            apt install curl -y
            apt install sudo -y
            sudo apt-get install \
            apt-transport-https \
            ca-certificates \
            curl \
            gnupg-agent \
            software-properties-common

      - run: 
          name: Docker Run
          command: |
            curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
            sudo apt-key fingerprint 0EBFCD88
            sudo add-apt-repository \
            "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
            $(lsb_release -cs) \
            stable"
            sudo apt-get update
            sudo apt-get install docker-ce docker-ce-cli containerd.io



      - run: sudo service docker start
      - run: docker status


        
# sudo service docker status
# docker run --ulimit nofile=32768:32768 --rm debian sh -c "ulimit -n" 32768

      - run: 
          name: Build image
          command: |
            docker build -t first_build .   
            echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
            docker context ls
            docker build -t first_build .          
      
#start it

workflows:
  build_and_test:
    jobs:
      - test
      - build:
          requires:
            - test
