version: 2.1

jobs:
  test:
    working_directory: ~/circleci-python
    docker:
      - image: "python:latest"
    steps:
      - checkout
      - run: python3 basi-add.py

  build:
    working_directory: ~/circleci-python
    docker:
      - image: cimg/base:2022.01
    steps:
      - checkout
      - run: 
          name: install docker
          command: |
            apt update -y
            apt install sudo
            USER root
            curl -fsSL https://get.docker.com -o get-docker.sh      
            sudo sh get-docker.sh
            USER 1001
            docker --version

      - run: 
          name: Build image
          command: |
            docker build -t first_build .   
            echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
            docker context ls
            docker build -t first_build .          
      
#start it

workflows:
  build_and_test:
    jobs:
      - test
      - build:
          requires:
            - test
