version: 2.1

jobs:
  test:
    working_directory: ~/circleci-python
    docker:
      - image: "python:latest"
    steps:
      - checkout
      - run: python3 basi-add.py

  build:
    working_directory: ~/circleci-python
    docker:
      - image: cimg/python:3.10.2
    steps:
      - checkout

      - setup_remote_docker:
          version: 19.03.13
          docker_layer_caching: true

      - run: 
          name: Build image
          command: |
            docker build -t first_build .   
            echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
            docker build -t first_build:v1 .
            docker push gowri45/vasu_2511          
      
#start it

workflows:
  build_and_test:
    jobs:
      - test
      - build:
          requires:
            - test




      # - run: 
      #     name: install docker
      #     command: |
      #       apt update -y
      #       apt install curl -y
      #       apt install sudo -y
      #       curl -fsSL https://get.docker.com -o get-docker.sh      
      #       sh get-docker.sh
      #       docker --version

      # - run: 
      #     name: Docker Run
      #     command: |
      #       export DOCKER_HOST=tcp://localhost:2375
      #       sudo service --status-all
      #       sudo service docker start