version: 2.1

jobs:
  test:
    working_directory: ~/circleci-python
    docker:
      - image: "circleci/python:3.8"
    steps:
      - checkout
      - run: python3 basi-add.py

  build:
    working_directory: ~/circleci-python
    docker:
      - image: "circleci/python:3.8"
    steps:
      - checkout
      - run:
          name: Login to docker
          command: |
            echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
            docker context ls
            docker build -t first_build .
      - run: 
          name: Build image
          command: echo "success"
             
      
#start it

workflows:
  build_and_test:
    jobs:
      - test
      - build:
          requires:
            - test
